#ifndef CONASAT_INCLUDE_ERROR_H_
#define CONASAT_INCLUDE_ERROR_H_

#define SUCCESS 0x00

#define BDG_ERROR_INVALID_PARAM 				0x01
#define BDG_ERROR_MEM_ALLOC 					0x02

#define USD_ERROR_IDLE_STATE      		0x01
#define USD_ERROR_SEND_IF_COND   	 	0x02
#define USD_ERROR_SD_SEND_OP_COND 		0x03
#define USD_ERROR_READ_OCR        		0x04
#define USD_ERROR_OLD_VERSION_NOT_CARD  0x05
#define USD_ERROR_CARD_NOT_DETECTED     0x06

//#define USD_ERROR_OP_COND_TIMEOUT 				0x02
//#define USD_ERROR_SET_BLOCKLEN_TIMEOUT 			0x03
//#define USD_ERROR_WRITE_BLOCK_TIMEOUT 			0x04
//#define USD_ERROR_WRITE_BLOCK_FAIL 				0x05
//#define USD_ERROR_READ_BLOCK_TIMEOUT 			0x06
//#define USD_ERROR_READ_BLOCK_DATA_TOKEN_MISSING 0x07

#endif /* CONASAT_INCLUDE_ERROR_H_ */
